### PR TITLE
Avoid net_kernel startup/shutdown races when peeking into ETS sys_dist table

### PR DESCRIPTION
**Pull request by slfritchie**
Avoid errors like this:

```
2013-08-08 14:55:26.301 [error] <0.7207.0> riak_sysmon_filter:get_node_map: error badarg @ [{ets,match_object,[sys_dist,'_'],[]},{ets,tab2list,1,[{file,"ets.erl"},{line,323}]},{riak_sysmon_filter,get_node_map,0,[{file,"src/riak_sysmon_filter.erl"},{line,360}]},{riak_sysmon_filter,handle_info,2,[{file,"src/riak_sysmon_filter.erl"},{line,249}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]
```

### CODE REVIEW

**Comment by jaredmorrow** [comment]
What is the status of this PR, something we still need/want?

**Comment by slfritchie** [comment]
It's an easy thing (and I believe a reviewer would concur), and we oughtta do it.

**Comment by jaredmorrow** [comment]
Thanks, I saw this linked from the EE ticket.  Think you can round up a reviewer post tech-preview to get this into 2.0?

**Comment by seancribbs** [comment]
@slfritchie This is straightforward and safe. I wonder about whether multiple try/catch in that function are necessary, but the impact is minimal. :+1:

**Pull request merged**
