### PR TITLE
Add runtime_health.triggers.process.long_schedule (based on the GC trigger definition)

### PR DESCRIPTION
**Pull request by slfritchie**
Add cuttlefish config to control the config of PR #11.

### CODE REVIEW

**Comment by russelldb** [comment]
Tests pass. Starting riak and looking at `app_helper:get_env(riak_sysmon)` shows changes to riak.conf entry reflected.

Wondering if this shouldn't be targeted against branch 2.0 though? If we can verify the target branch, happy to +1.

**Comment by russelldb** [comment]
+1 7bc72b8

**Comment by slfritchie** [comment]
Merging to develop, then will separately merge develop to "2.0" branch, thanks for pointing that out!

**Comment by seancribbs** [comment]
I know this is onerous, but schema changes should get a CSE +1 as well. (For future reference)

**Comment by russelldb** [comment]
makes sense, did not know. Assume same for Scott (though he will tell you, I'm sure) Sorry

**Pull request merged**
