### PR TITLE
moved riak_sysmon bits of cuttlefish schema here, with tests

### PR DESCRIPTION
**Pull request by joedevivo**

### CODE REVIEW

**Comment by slfritchie** [comment]
Hiya.  It'd be spiffy if there were some way to keep only one copy of the constants, but that would involve computers  even more.

For the test, I'm wondering if you'd object to something like this?  Or is it too ugly?

```
-define(PROCESS_LIMIT, 30).
-define(PLUS1, ((X) + 1)).

basic_schema_test() ->
%% ....
    cuttlefish_unit:assert_config(Config, "riak_sysmon.process_limit", ?PROCESS_LIMIT),

%% ....
override_schema_test() ->
    Conf = [
        {["riak_sysmon", "process_limit"], ?PLUS1(?PROCESS_LIMIT)},
%% ....
    cuttlefish_unit:assert_config(Config, "riak_sysmon.process_limit", ?PLUS1(?PROCESS_LIMIT)),
```

**Comment by joedevivo** [comment]
as tests go, I'm very mush a supporter of being able to understand what's being asserted only by reading the single line in question. Using macros like that is probably the best suggestion I've heard about how to set those values programmatically. I'll give it a try later today.

**Comment by joedevivo** [comment]
@slfritchie  I gave it a try. I'm not in love with the new implementation over the old one. I leave it to you to decide which implementation of the test you want in the project, and I'll merge whichever you choose.

**Comment by slfritchie** [comment]
How about the scatter-shot approach?  Leave the macros in this one, and use a non-macro approach for other repos, and see which is less hated 6 months from now?  +1 on ce1a0e2 and prior, thanks.

**Pull request merged**
