### PR TITLE
Add support for long_schedule

### PR DESCRIPTION
**Pull request by lpgauth**
long_schedule was added to system_monitor in R16B01
http://www.erlang.org/doc/man/erlang.html#system_monitor-0

### CODE REVIEW

**Comment by slfritchie** [comment]
Hi, sorry for the delay.  I've scheduled a milestone for the Riak release schedule.

**Comment by slfritchie** [comment]
I took a look at the VM source code.  The time accounting for `long_schedule` is _not_ done using the `erlang:now()` time source, hooray.

**Comment by lpgauth** [comment]
Yeah, better late then never :+1:

**Comment by slfritchie** [comment]
@lpgauth It wasn't necessary that your PR got caught in Riak 2.0.0 code freeze that took too long, but it did, my apologies!

**Pull request merged**
